name: netflix
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  lottie: ^3.1.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  flutter_inappwebview: ^6.0.0
  remixicon: ^1.2.0
  http: ^1.2.1
  get_it: ^7.7.0
  cached_network_image: ^3.3.1
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  flutter_lints: ^3.0.2
  url_launcher: ^6.2.6
  better_player: ^0.0.83
  auto_orientation: ^2.3.1
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/netflix_logo.png"
flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Netflix
      fonts:
        - asset: assets/fonts/NetflixSans-Regular.otf
          weight: 400
        - asset: assets/fonts/NetflixSans-Light.otf
          weight: 300
        - asset: assets/fonts/NetflixSans-Medium.otf
          weight: 500
        - asset: assets/fonts/NetflixSans-Bold.otf
          weight: 600
